<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <title>Clients</title>
</head>
<body>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-table@1.24.0/dist/bootstrap-table.min.css">

<script src="https://cdn.jsdelivr.net/npm/bootstrap-table@1.24.0/dist/bootstrap-table.min.js"></script>
<h1>Clients</h1>
<form action="/index.php" method="get">
    <div class="form-row">
        <div class="form-group col-md-2">
            <label for="country">Country</label>
            <input type="text" class="form-control" id="country" name="country" aria-describedby="countryHelp" placeholder="Enter country">
            <small id="countryHelp" class="form-text text-muted">Add more then one country use , </small>
        </div>
        <div class="form-group col-md-2">
            <label for="city">City</label>
            <input type="text" class="form-control" id="city" name="city" placeholder="City">
        </div>
        <div class="form-group col-md-2">
            <label for="isactive">Active</label>
            <input type="text" class="form-control" id="active" name="isActive" placeholder="Active">
        </div>
        <div class="form-group col-md-2">
            <label for="gender">Gender</label>
            <input type="text" class="form-control" id="gender" name="gender" placeholder="Gender">
        </div>
        <div class="form-group col-md-2">
            <label for="birthdate_from">BD From</label>
            <input type="date" class="form-control" id="birthdate_from" name="birthDate_from">
            <label for="birthdate_to">DB To</label>
            <input type="date" class="form-control" id="birthdate_to" name="birthDate_to">
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
<br>
<table id="table"  data-pagination="true">
    <thead>
    <tr>
        <th data-field="client_id">ID</th>
        <th data-field="country">Country</th>
        <th data-field="city">City</th>
        <th data-field="isactive">Active</th>
        <th data-field="gender">Gender</th>
        <th data-field="birthdate">Birth Date</th>
        <th data-field="salary">Salary</th>
        <th data-field="haschildren">Children</th>
        <th data-field="familystatus">Family Status</th>
        <th data-field="registrationdate">Registration Date</th>
    </tr>
    </thead>
</table>

<script>
    var $table = $('#table')

    $(function() {
        var data = <?php echo getData();?>;
        $table.bootstrapTable({data: data})
    })
</script>
</body>
</html>
