<?php
/**
 * @var Core\Block\Block $this
 */
?>
<div class="custom-bg text-dark">
    <div class="d-flex align-items-center justify-content-center min-vh-100 px-2">
        <div class="text-center">
            <h3>Load customer file</h3>
            <form enctype="multipart/form-data" action="/load/file" method="post">
                <div class="form-row">
                    <div class="form-group col-md-8">
                        <input type="hidden" name="MAX_FILE_SIZE" value="5242880" />
                        <input type="file" name="file" accept="text/csv" class="form-control"  aria-label="Upload">
                    </div>
                    <div class="form-group col-md-2">
                        <input type="submit" value="Upload and parse file" class="btn btn-dark fw-semibold rounded-pill px-4 py-2 custom-btn" />
                    </div>
                </div>
            </form>
            <?php
            $this->getData('importResult');
            $this->getData('uploadResult');
            if ($this->getData('uploadResult') && $this->getData('importResult')){ ?>
                <a href="/analyze" class="btn btn-dark fw-semibold rounded-pill px-4 py-2 custom-btn">
                    Open search page
                </a>
            <?php
            } elseif ($this->getData('uploadResult') === false || $this->getData('importResult') === false) {
                echo 'Sorry, something went wrong. Please try again later.';
            }?>
        </div>
    </div>
</div>
